
-- create
CREATE TABLE CUSTOMERS (
  cust_id INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

-- create
CREATE TABLE TRANS (
  trans_id INTEGER PRIMARY KEY,
  cust_id  INTEGER NOT NULL,
  amount   INTEGER NOT NULL
);

-- insert
INSERT INTO CUSTOMERS VALUES (1, 'Clark');
INSERT INTO CUSTOMERS VALUES (2, 'Dave');
INSERT INTO CUSTOMERS VALUES (3, 'Ava');

-- insert
INSERT INTO TRANS VALUES (1, 1, 10);
INSERT INTO TRANS VALUES (2, 2, 11);
INSERT INTO TRANS VALUES (3, 3, 12);

-- fetch 
SELECT * FROM CUSTOMERS;
